version: "3.7"
services:
  athena:
    build:
      context: ./
      dockerfile: Dockerfile.local
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
    ports: 
      - 5000:5000
    volumes:
      - ./api:/app/api
