version: "3.7"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.local
    entrypoint:
      - gunicorn
      - --worker-class=geventwebsocket.gunicorn.workers.GeventWebSocketWorker
      - --bind=0.0.0.0:5000
      - -w=1
      - app:app
      - --reload
      - --timeout=300
      - --capture-output
      - --log-level=debug
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
    ports: 
      - 5000:5000
    volumes:
      - ./api:/app/api
      - ./app.py:/app/app.py
